[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python_kms"
version = "0.1.0"
description = "Proyecto KMS en Python"
authors = [
    { name="Ariel Díaz", email="ariel@example.com" }
]
dependencies = []
